### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by max3903** [OCA/survey#2]
# Roadmap
- [ ] add new type of answer by @bjoliveau 

For example "percent" type : one respondent is asked how to spread his activity as a percentage from a preconfigured list pending precise values. Workaround : If no requirement for precise value, it can be configured ranges of values in a list of choices.
- [ ] allow adding comment on each item for multiple choice answer
- [ ] format "date time" type to set date and time or only date or only time
- [ ] allow subquestions. Very useful with conditional_questions to loop on a page or series of questions
- [ ] allow editing or inserting Odoo blocks in website survey inside of the question-answer group and not only around or after. For example, one respondent is asked to vote about pictures selection.
- [ ] offer choice to the survey's administrator to display information from an existing object (for example : res.partner)
- [ ] extend the existing notation to finely evaluate or profile by answering and generate actions (for example : generate sale order and sale order lines depending on respondent answers)

**Comment by bjoliveau** [comment]
For your info, we have just begun the conception of new type of answer "percent".
The module "survey_percent_question" will be offered in this repo if OCA accept.
